### PR TITLE
Blog post about Fastly CDN sponsorship

### PR DESCRIPTION
**Pull request by andyshinn**

### CODE REVIEW

**Comment by progrium** [comment]
Needs `author` field in meta data. Title with Alpine would be better. Maybe: "Fastly CDN speeds up Alpine package installs"

Otherwise :+1:

**Comment by andyshinn** [comment]
Does it? I copied it from another post that didn't have it. Looks like at least two don't have it and they work. Modified title.

**Comment by progrium** [comment]
Oh. Well they should have had it too. I should make the generator include it. Are you trying to specifically avoid it?

**Comment by andyshinn** [comment]
No, it just didn't seem necessary. It is added.

**Comment by progrium** [comment]
It helps from a content "voice" perspective since we don't have a single public facing voice, nor should we have one as I think it's best to emphasize the personal element. I think it's really helpful to readers to know the person these posts are coming from.

**Comment by progrium** [comment]
You should be able to `gun deploy`

**Comment by andyshinn** [comment]
I don't have a local Ruby environment. Can you deploy it?

**Comment by progrium** [comment]
Done

**Pull request merged**
